import assert from 'node:assert/strict';
import test from 'node:test';

import { SOURCE_URL } from '../scripts/observatoire-source.mjs';
import { assertNoPersonalData } from '../scripts/privacy-guard.mjs';

test('the ingestion uses the canonical URL generated by the official API tester', () => {
  const url = new URL(SOURCE_URL);

  assert.equal(url.origin, 'https://opppp.cartes.xyz');
  assert.equal(url.pathname, '/api/elements.json');
  assert.equal(url.searchParams.get('limit'), '5000');
  assert.equal(url.searchParams.get('categories'), '3,4,6');
});

test('the privacy guard rejects an email without echoing it into CI logs', () => {
  const address = 'personne@example.com';

  assert.throws(
    () => assertNoPersonalData({ authorEmail: address }),
    (error) => {
      assert.match(error.message, /Fuite de données personnelles/);
      assert.doesNotMatch(error.message, new RegExp(address.replace('.', '\\.')));
      return true;
    },
  );
});

test('the privacy guard rejects private field names even when their value is empty', () => {
  assert.throws(
    () => assertNoPersonalData({ subscriberEmails: [] }),
    /Fuite de données personnelles/,
  );
  assert.throws(
    () => assertNoPersonalData({ authorEmail: '' }),
    /Fuite de données personnelles/,
  );
});

test('the privacy guard accepts a whitelisted public payload', () => {
  assert.doesNotThrow(() =>
    assertNoPersonalData({ author: 'Camille Martin', officialUrl: 'https://example.com/photo/1' }),
  );
});
