import assert from 'node:assert/strict';
import test from 'node:test';

import { deliveryImageUrl, deliveryImageUrls } from '../scripts/image-delivery.mjs';
import { SOURCE_URL } from '../scripts/observatoire-source.mjs';
import { assertNoPersonalData } from '../scripts/privacy-guard.mjs';

test('the ingestion uses the canonical URL generated by the official API tester', () => {
  const url = new URL(SOURCE_URL);

  assert.equal(url.origin, 'https://opppp.cartes.xyz');
  assert.equal(url.pathname, '/api/elements.json');
  assert.equal(url.searchParams.get('limit'), '5000');
  assert.equal(url.searchParams.get('categories'), '3,4,6');
});

test('image delivery uses the validated CDN for both official upstream hosts', () => {
  assert.equal(
    deliveryImageUrl('https://opppp.cartes.xyz/uploads/opppp/images/elements/photo 1.jpg'),
    'https://i0.wp.com/opppp.cartes.xyz/uploads/opppp/images/elements/photo%201.jpg?ssl=1',
  );
  assert.equal(
    deliveryImageUrl('https://observatoire-photo.paris/uploads/opppp/images/elements/photo.jpg'),
    'https://i0.wp.com/observatoire-photo.paris/uploads/opppp/images/elements/photo.jpg?ssl=1',
  );
});

test('image delivery normalizes and deduplicates an upstream image list', () => {
  const original = 'https://opppp.cartes.xyz/uploads/opppp/images/elements/photo.jpg';
  assert.deepEqual(deliveryImageUrls([original, original, null, 'https://example.com/photo.jpg']), [
    'https://i0.wp.com/opppp.cartes.xyz/uploads/opppp/images/elements/photo.jpg?ssl=1',
  ]);
});

test('image delivery rejects arbitrary hosts and non-image paths', () => {
  assert.equal(deliveryImageUrl('https://example.com/uploads/opppp/images/elements/photo.jpg'), undefined);
  assert.equal(deliveryImageUrl('https://opppp.cartes.xyz/api/elements.json'), undefined);
  assert.equal(
    deliveryImageUrl(
      'https://opppp.cartes.xyz/uploads/opppp/images/elements/%2F..%2Fapi/elements.json',
    ),
    undefined,
  );
  assert.equal(
    deliveryImageUrl(
      'https://opppp.cartes.xyz/uploads/opppp/images/elements/%252e%252e%252Fphoto.jpg',
    ),
    undefined,
  );
  assert.equal(
    deliveryImageUrl('https://opppp.cartes.xyz/uploads/opppp/images/elements/not-an-image.txt'),
    undefined,
  );
  assert.equal(
    deliveryImageUrl('https://opppp.cartes.xyz:443/uploads/opppp/images/elements/photo.jpg'),
    undefined,
  );
  assert.equal(
    deliveryImageUrl('https://opppp.cartes.xyz/uploads/opppp/images/elements/photo.jpg?ssl=0'),
    undefined,
  );
  assert.equal(
    deliveryImageUrl('https://opppp.cartes.xyz/uploads/opppp/images/elements/photo.jpg?'),
    undefined,
  );
  assert.equal(
    deliveryImageUrl('https://opppp.cartes.xyz/uploads/opppp/images/elements/photo.jpg#'),
    undefined,
  );
  assert.equal(deliveryImageUrl('http://opppp.cartes.xyz/uploads/opppp/images/elements/photo.jpg'), undefined);
});

test('the privacy guard rejects an email without echoing it into CI logs', () => {
  const address = 'personne@example.com';

  assert.throws(
    () => assertNoPersonalData({ authorEmail: address }),
    (error) => {
      assert.match(error.message, /Fuite de données personnelles/);
      assert.doesNotMatch(error.message, new RegExp(address.replace('.', '\\.')));
      return true;
    },
  );
});

test('the privacy guard rejects private field names even when their value is empty', () => {
  assert.throws(
    () => assertNoPersonalData({ subscriberEmails: [] }),
    /Fuite de données personnelles/,
  );
  assert.throws(
    () => assertNoPersonalData({ authorEmail: '' }),
    /Fuite de données personnelles/,
  );
});

test('the privacy guard accepts a whitelisted public payload', () => {
  assert.doesNotThrow(() =>
    assertNoPersonalData({ author: 'Camille Martin', officialUrl: 'https://example.com/photo/1' }),
  );
});
